### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by Palla551** [PRIS2/ji#1]
#### Occurred on:
+ **Commit**:  0450d89c87ee9b62d72c8686530a72a5b77cf29d
+ **File**:    [app.py](https://github.com/PRIS2/ji/blob/0450d89c87ee9b62d72c8686530a72a5b77cf29d/app.py)
+ **LineNum**: [13](https://github.com/PRIS2/ji/blob/0450d89c87ee9b62d72c8686530a72a5b77cf29d/app.py#L13)
+ **Code**:    `if(user_param.isdigit()): user_decision = int(user_param)`

    
#### Currently on:
+ **Commit**:  047c2711887831818fd7b04408e593f8aaf9044e
+ **File**:    [app.py](https://github.com/PRIS2/ji/blob/047c2711887831818fd7b04408e593f8aaf9044e/app.py)
+ **LineNum**: [16](https://github.com/PRIS2/ji/blob/047c2711887831818fd7b04408e593f8aaf9044e/app.py#L16)

**Comment by luxor-g** [comment]
Detalle tonto a arreglar, yo siempre uso editorconfig que te arregla eso y mas.

Referencia: https://github.com/PRIS2/Psi/blob/master/.editorconfig

**Comment by Palla551** [comment]
Se han aplicado los cambios y se ha resuelto este Issue

https://github.com/PRIS2/ji/blob/047c2711887831818fd7b04408e593f8aaf9044e/app.py#L16
