### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by luxor-g** [PRIS2/ji#2]
https://github.com/PRIS2/ji/blob/5b97eb76a62afb354f4773c73bd9e237d720a252/app.py#L7

"Welcom"

**Comment by Palla551** [comment]
https://github.com/PRIS2/ji/blob/3bace3ae4026c31b12df11897fd8778fe70d4860/app.py#L7

Tras una pequeña modificación se han resuelto los errores aqui mencionados
