### ISSUE TITLE
Falta de .gitignore

### ISSUE THREAD

**Issue by luxor-g** [PRIS2/ji#4]
Añadir .gitignore para no subir las carpetas irrelevantes: __pycache__

Ya que estamos utilizando únicamente Python podemos simplemente hacer uso del siguiente .gitignore: https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by Palla551** [comment]
Siguiendo con la sugerencia, se ha implementado un .gitignore acorde

https://github.com/PRIS2/ji/blob/3bace3ae4026c31b12df11897fd8778fe70d4860/.gitignore
